// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGK6sXvNmgQ6C6A79WAuvr-ySmzXakquI',
    appId: '1:1033041739513:web:05cfb443f2ffa961c5ac28',
    messagingSenderId: '1033041739513',
    projectId: 'sahabatmahasiswa',
    authDomain: 'sahabatmahasiswa.firebaseapp.com',
    storageBucket: 'sahabatmahasiswa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2LiPP8HYZk9iCv9C5IHFc2bh3AWi5wpk',
    appId: '1:1033041739513:android:ec20779665f48489c5ac28',
    messagingSenderId: '1033041739513',
    projectId: 'sahabatmahasiswa',
    storageBucket: 'sahabatmahasiswa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH0ehAYLODPA1KJe34AtQLH7lciRX_NHM',
    appId: '1:1033041739513:ios:990dc827b8723ee3c5ac28',
    messagingSenderId: '1033041739513',
    projectId: 'sahabatmahasiswa',
    storageBucket: 'sahabatmahasiswa.appspot.com',
    iosBundleId: 'com.example.loginSahabatMahasiswa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH0ehAYLODPA1KJe34AtQLH7lciRX_NHM',
    appId: '1:1033041739513:ios:bea52f0883fdbd21c5ac28',
    messagingSenderId: '1033041739513',
    projectId: 'sahabatmahasiswa',
    storageBucket: 'sahabatmahasiswa.appspot.com',
    iosBundleId: 'com.example.loginSahabatMahasiswa.RunnerTests',
  );
}
